name: watchn
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  device_preview:
  hydrated_bloc:
  flutter_bloc:
  flutter_screenutil:
  flutter_svg:
  cupertino_icons: ^1.0.4
  equatable:
  pinput: ^2.2.9
  page_transition:
  introduction_screen: ^3.0.2
  dotted_border: ^2.0.0+2
  flutter_rating_bar: ^4.0.1
  video_player: ^2.4.7
  google_maps_flutter: ^2.2.0
  image_picker:
  http:
  shared_preferences:
  geocoding:
  geolocator: ^9.0.0
  permission_handler:
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  flutter_lints:
flutter_gen:
  output: lib/gen/
  line_length: 80

  # Optional
  integrations:
    flutter_svg: true
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icon/
    - assets/


  fonts:
    - family: HelveticaNowDisplay
      fonts:
        - asset: assets/fonts/HelveticaNowDisplay-Bold.ttf
        - asset: assets/fonts/HelveticaNowDisplay-Light.ttf
        - asset: assets/fonts/HelveticaNowDisplay-Medium.ttf
        - asset: assets/fonts/HelveticaNowDisplay-Regular.ttf
